### PR TITLE
Fix homebrew style

### PR DESCRIPTION
**Pull request by acidlynx**
Fix homebrew bottle style.

I just ran `brew style --fix`

### CODE REVIEW

**Comment by airtonix** [comment]
lgtm

**Comment by twsheehan** [comment]
I followed the same command as prescribed by the console output and as described above which did a find style infractions in all formulae. I observed in any new session and running `brew update` or other `brew` commands and the same issue would be logged to the console.

The solution for me was to use `brew style --fix applesimutils` which also seems to coincide with the fixed: https://github.com/aws/homebrew-tap/pull/188

**Comment by acidlynx** [comment]
@LeoNatan Hello! Could you please check this PR.
Thanks!

**Comment by LeoNatan** [comment]
I'm no longer involved with this project or Wix.

**Comment by SimenB** [comment]
Any idea who to ping? You've got 100% of the commits in this repo 😀

**Comment by acidlynx** [comment]
> I'm no longer involved with this project or Wix.

Oh. Sorry. I'll find actual maintainers. Thanks for the info!

**Comment by danilobuerger** [comment]
Maybe @alon-ha ?

**Comment by d4vidi** [comment]
Thanks guys, checking 🙏🏻

**Comment by acidlynx** [comment]
> Thanks guys, checking 🙏🏻

Thank you!

**Pull request merged**
