### PR TITLE
fix: AppleSimUtils 0.9.6 SHA256.

### PR DESCRIPTION
**Pull request by asafkorem**
Update SHA256 with actual SHA256 from error message when installing applesimutils:
```
Error: applesimutils: SHA256 mismatch
Expected: f597cc8f4c09bf130921087565762d39eb9e79436df3ce8f5b700e372f5258bb
  Actual: 0abd6a10f0fa5f7008799c06c59836b690ca2707bf9cb8a62095ecbd87363e6d
```

### CODE REVIEW

**Comment by arthuralee** [comment]
@asafkorem im seeing this on multiple machines:
```
==> Downloading https://github.com/wix/AppleSimulatorUtils/releases/download/0.9
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 0abd6a10f0fa5f7008799c06c59836b690ca2707bf9cb8a62095ecbd87363e6d
  Actual: 49e54d54a7ab60829b89ba9c8864d02be2a1adc2c3334575a4143d4a828cdc18
    File: /Users/arthur.lee/Library/Caches/Homebrew/downloads/9a2b9fdcf958d7ff5440a521a8228343a20ac3cc41bfba0d0c26790d3250ee24--applesimutils-0.9.6.arm64_big_sur.bottle.tar.gz
To retry an incomplete download, remove the file above.
```

I also manually checked the SHA of the tarball downloaded from github and found that the SHA was the same as the above

**Comment by asafkorem** [comment]
@arthuralee interesting, checking 👀

**Comment by arthuralee** [comment]
I did see this run in the react-native repo that confirms the SHA256 that you committed https://app.circleci.com/pipelines/github/facebook/react-native/14124/workflows/0b266176-2327-47e2-b1ca-a240dc134a7a/jobs/265066 so im pretty confused now..

**Comment by asafkorem** [comment]
@arthuralee 
please try the following:

brew tap wix/brew
brew update
brew install applesimutils

**Comment by arthuralee** [comment]
cant install `wix/applesimutils`, had to install just `applesimutils` or `wix/brew/applesimutils`
```
➜  ~ brew tap wix/brew
brew update
brew install wix/brew/applesimutils
Already up-to-date.
applesimutils 0.9.5 is already installed but outdated (so it will be upgraded).
==> Downloading https://github.com/wix/AppleSimulatorUtils/releases/download/0.9.6/applesimuti
Already downloaded: /Users/arthur.lee/Library/Caches/Homebrew/downloads/9a2b9fdcf958d7ff5440a521a8228343a20ac3cc41bfba0d0c26790d3250ee24--applesimutils-0.9.6.arm64_big_sur.bottle.tar.gz
Error: applesimutils: SHA256 mismatch
Expected: 0abd6a10f0fa5f7008799c06c59836b690ca2707bf9cb8a62095ecbd87363e6d
  Actual: 49e54d54a7ab60829b89ba9c8864d02be2a1adc2c3334575a4143d4a828cdc18
    File: /Users/arthur.lee/Library/Caches/Homebrew/downloads/9a2b9fdcf958d7ff5440a521a8228343a20ac3cc41bfba0d0c26790d3250ee24--applesimutils-0.9.6.arm64_big_sur.bottle.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by asafkorem** [comment]
@arthuralee can you please try again? I hope this solves the issue for you: https://github.com/wix/homebrew-brew/pull/18.

**Comment by arthuralee** [comment]
Works great now! thank you

**Pull request merged**
